.pragma library

var PADDING_LARGE   = 8
var PADDING_MEDIUM  = 6
var PADDING_SMALL   = 4

var DEFAULT_MARGIN  = 16

var FONT_FAMILY     = 'Nokia Pure Text'
var FONT_XLARGE     = 32
var FONT_LARGE      = 28
var FONT_SLARGE     = 26
var FONT_DEFAULT    = 24
var FONT_LSMALL     = 22
var FONT_SMALL      = 20
var FONT_XSMALL     = 18
var FONT_XXSMALL    = 16

var COLOR_FOREGROUND                    = '#191919'
var COLOR_INVERTED_FOREGROUND           = '#FFFFFF'
var COLOR_BUTTON_DISABLED_FOREGROUND    = '#B2B2B4'

var HEADER_DEFAULT_HEIGHT_PORTRAIT  = 72
var HEADER_DEFAULT_HEIGHT_LANDSCAPE = 52

var HEADER_DEFAULT_TOP_SPACING_PORTRAIT     = 20
var HEADER_DEFAULT_TOP_SPACING_LANDSCAPE    = 16

var LIST_ITEM_HEIGHT_DEFAULT    = 80
var LIST_ITEM_HEIGHT_SMALL      = 64
